CREATE TABLE USER (
	id INT PRIMARY KEY,
	full_name VARCHAR(255) NOT NULL,
	birth_date DATE NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	hashed_password VARCHAR(255) NOT NULL,
	lang VARCHAR(10) NOT NULL DEFAULT 'fr'
);


CREATE TABLE EVENT (
	id INT PRIMARY KEY,
	date DATE NOT NULL,
	description TEXT NOT NULL,
	person_id INT NOT NULL,
	FOREIGN KEY (person_id) REFERENCES USER(id) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE MESSAGE (
	id INT PRIMARY KEY,
	event_id INT NOT NULL,
	source VARCHAR(255) NOT NULL,
	content TEXT NOT NULL,
	FOREIGN KEY (event_id) REFERENCES EVENT(id) ON DELETE CASCADE ON UPDATE CASCADE
);
